# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
pandoc_version: 1.18
python: 3.5

sudo: required
cache: packages

services:
  - mongodb
  
before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - MONGODB_URL=\"mongo://travis:test@localhost:27017\
    
before_install:
  - sudo apt-get install python-pip
  - sudo pip install --upgrade pip
  - python -m pip install --upgrade pymongo
  - sudo pip install jsonschema
  - sudo pip install -U bson
  - sudo apt-get install r-base-dev
  - tlmgr install index
  - sudo apt-get update

r_packages:
  - devtools
  - roxygen2
  - testthat
  - reticulate
  - R6
  - covr
  - knitr
  - rmarkdown
  - geojsonR
  - data.table

  
after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'
  
warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change
